### ISSUE TITLE
improve performance on non-mr simrank

### ISSUE THREAD

**Issue by zihaolucky** [amir-f/delta-simrank#1]
It's too slow to generate possible pairs in for loop, get it out of this loop would be fine.

```
try:
    pool.map(simrank_map, 
            [(u, v, pred_func(u), pred_func(v)) for u, v in itertools.product(nodes, nodes)],
            chunksize=CHUNK_SIZE)
except:
    logging.error('Exception in pool map')
    traceback.print_exc()
```

**Comment by amir-f** [comment]
IIUC, those are a generators. Both the second argument of the `map` and `itertools.product(nodes, nodes)`. So creating the generators is probably very cheap.

You can try it out by doing:

``` python
n = range(10000)
r = itertools.product(n, n)
```

executing those lines happens almost instantaneously while iterating over them takes longer

``` python
print len(list(r))
```

**Comment by zihaolucky** [comment]
Thanks for reply :)

yes, `r` is a generator. But `[(u, v, pred_func(u), pred_func(v)) for u, v in itertools.product(nodes, nodes)]` creates a new list, which is time consuming.

**Comment by amir-f** [comment]
You're right. I think I can change it to a generator instead of list comprehension rather than materializing the list once outside the loop.
That'd help with memory usage as well

**Comment by zihaolucky** [comment]
Not sure if it's okay to put a generator into the second parameter of `pool.map`.

Maybe this post would do the trick. http://stackoverflow.com/questions/5318936/python-multiprocessing-pool-lazy-iteration

**Comment by amir-f** [comment]
You're right. I'll fix it soon.
